### ISSUE TITLE
Request for Clarification on Code Origin and Attribution

### ISSUE THREAD

**Issue by asonnleitner** [kosarlukascz/wpc-smartform#1]
Dear @kosarlukascz,

Upon careful review of this project, I've noticed patterns in the code that are highly indicative of AI-assisted generation, particularly resembling output from OpenAI models. However, I couldn't find any mention of AI usage or appropriate attribution in the repository documentation.

Given these observations, I have some important questions:

1. Was AI-assisted coding, particularly from OpenAI, used in developing this project?
2. If so, which specific parts of the codebase were created with AI assistance?
3. Could you please add appropriate attribution and ensure compliance with OpenAI's usage policies and licensing terms?

Transparency about AI usage is crucial for:

- Proper attribution
- Compliance with AI tool licensing requirements
- Helping users and contributors understand the code's origin

I appreciate your attention to this matter and look forward to your clarification. If I've misunderstood anything, please let me know.

In the interest of full transparency, I want to disclose that this issue was composed with the assistance of AI. I believe in practicing the same openness I'm requesting.

Thank you,

**Comment by kosarlukascz** [comment]
Hi, Andreas,
I appreciate your interest in my code and my repositories. You are right that I have been using AI - but only to create the readme.

Of course, you're right that I didn't mention this fact, I've already corrected that.

Thank you for your interest and for pointing it out.
